POST http://localhost:8080/api/task
Content-Type: application/json

{
  "title": "title2",
  "desc": "desc2",
  "status": "SCHEDULED",
  "taskType": "EXAM",
  "date": "2023-10-12T14:26:36.588Z",
  "dateCreated": "2023-10-27T11:08:55.241Z",
  "dateUpdated": null,
  "url": "url"
}